name             'dse'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures dse'
long_description 'Installs/Configures dse'
version          '0.1.0'

depends 'selinux'
depends 'hostsfile'
depends 'yum'